### PR TITLE
cargo audit fix

### LINKED ISSUE #2: Update chrono to the latest version
`cargo audit` results:
```
Crate:     chrono
Version:   0.4.19
Title:     Potential segfault in `localtime_r` invocations
Date:      2020-11-10
ID:        RUSTSEC-2020-0159
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:  Upgrade to >=0.4.20
Dependency tree:
chrono 0.4.19
└── cron_schedule 0.2.2

Crate:     time
Version:   0.1.44
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.44
└── chrono 0.4.19
    └── cron_schedule 0.2.2

error: 2 vulnerabilities found!
```

### PR DESCRIPTION
**Pull request by Buckram123**
Closes #2

### CODE REVIEW

**Comment by Buckram123** [comment]
adding clippy warnings fixes and format, @TrevorJTClarke tell me, if I should revert those commits

File: src/queries.rs [hunk 1]
```diff
@@ -17,13 +17,12 @@ pub struct NextAfterQuery {
...
 impl NextAfterQuery {
     pub fn from(after: &u64) -> NextAfterQuery {
-        let rem = after.clone() % NANOS;
-        let secs = ((after.clone() - rem) / (NANOS * SECONDS)) + 1;
-        let initial_datetime = DateTime
-            ::from_utc(
-                NaiveDateTime::from_timestamp(secs as i64, 0), 
-                Utc
-            );
+        let rem = *after % NANOS;
```
Comment (mikedotexe) [inline src/queries.rs:20]: watch out everyone, this guy is gettin' Rusty on us

**Comment by Buckram123** [comment]
> In JavaScript, I know about "yarn link" and "npm link" which let you symlink your dependencies in other project, and "pretend" that your primary project is using updates to a dependency… Is there something similar to Rust?
> 
> Basically, if you have been able to test the CronCat Manager contract with these new changes, could you share a good way to do that? (If we didn't do that, that's fine, just curious)

@mikedotexe Yep, tested it with this PR:
https://github.com/CronCats/cw-croncat/pull/200/files#diff-7658670fc10541675b730cd4a2f595229151be89709c05393a908d44b9220ce0R20
It is the only reason why this PR is draft right now

**Review by TrevorJTClarke — APPROVED** [review]
